### ISSUE TITLE
v1.3.0 - tracking issue

### ISSUE THREAD

**Issue by pitkley** [pitkley/dfw#528]
- [x] Look into getting #700 merged.
- [x] Comment on and close #411.
- [x] Probably retarget #277 to a different release/milestone.
